In [3]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
import pyspark
from delta import *
import os

In [4]:

# Build Spark session with Delta configurations and Hive support
builder = SparkSession.builder.appName("silvertogold") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .config("spark.hadoop.io.native.lib.available", "true") \
    .config("spark.jars.packages", "org.apache.hive:hive-exec:2.3.9")  \
    .config("spark.driver.memory", "4g") \
    .config("spark.executor.memory", "4g") \
# Enable Hive support explicitly and get Spark session
spark = configure_spark_with_delta_pip(builder.enableHiveSupport()).getOrCreate()

# Optionally, you can test by running a Hive query
spark.sql("CREATE TABLE IF NOT EXISTS test_hive_table (name STRING, age INT) USING hive")
spark.sql("SELECT * FROM test_hive_table")
spark.sql("select count(*) from silver.location").show()

+--------+
|count(1)|
+--------+
| 1006477|
+--------+

In [5]:
# List of external silver tables
silver_tables = [
    "silver.location",
    "silver.payment",
    "silver.payment_method",
    "silver.payment_status",
    "silver.request",
    "silver.trip",
    "silver.user",
    "silver.vehicle",
    "silver.vehicle_make"
] 
print(silver_tables)

['silver.location', 'silver.payment', 'silver.payment_method', 'silver.payment_status', 'silver.request', 'silver.trip', 'silver.user', 'silver.vehicle', 'silver.vehicle_make']

In [6]:
landing_location = os.path.join(os.getcwd())
bronze_location = os.path.join(landing_location, "bronze")
silver_location = fr"{os.getcwd()}/silver"
gold_location = fr"{os.getcwd()}/gold"
print(silver_tables)
print(os.getcwd())
print(bronze_location)
print(silver_location)
print(gold_location)

['silver.location', 'silver.payment', 'silver.payment_method', 'silver.payment_status', 'silver.request', 'silver.trip', 'silver.user', 'silver.vehicle', 'silver.vehicle_make']
e:\DEPIfINALpROJECT\DATABASEcSV
e:\DEPIfINALpROJECT\DATABASEcSV\bronze
e:\DEPIfINALpROJECT\DATABASEcSV/silver
e:\DEPIfINALpROJECT\DATABASEcSV/gold

In [7]:
# Verify the current schema
print("Current Schema:")
spark.sql("use silver")
spark.sql("SELECT current_database()")

# List all tables in the bronze schema
print("Tables in silver schema:")
spark.sql("SHOW TABLES IN silver").show()
spark.sql("SELECT * FROM silver.location LIMIT 1").show()
spark.sql("SELECT * FROM silver.payment LIMIT 1").show()


# Describe the history of the Delta table
print("Describing history for silver.location:")

Current Schema:
Tables in silver schema:
+---------+--------------+-----------+
|namespace|     tableName|isTemporary|
+---------+--------------+-----------+
|   silver|      location|      false|
|   silver|       payment|      false|
|   silver|payment_method|      false|
|   silver|payment_status|      false|
|   silver|       request|      false|
|   silver|          trip|      false|
|   silver|          user|      false|
|   silver|       vehicle|      false|
|   silver|  vehicle_make|      false|
+---------+--------------+-----------+

+-----------+------------+-----------+-------------------+--------------------+--------------------+
|location_id|   longitude|   latitude|    processing_date|record_modified_date|         record_hash|
+-----------+------------+-----------+-------------------+--------------------+--------------------+
|     865126|-74.00482178|40.73152542|2024-10-13 19:44:50|2024-10-08 09:46:...|000040462abe6e0e6...|
+-----------+------------+-----------+-------------------+--------------------+--------------------+

+----------+-----------------+-----------------+-------------------+--------------------+--------------------+
|payment_id|payment_method_id|payment_status_id|    processing_date|record_modified_date|         record_hash|
+----------+-----------------+-----------------+-------------------+--------------------+--------------------+
|      NULL|             NULL|             NULL|2024-10-13 19:45:08|2024-10-08 09:47:...|e3b0c44298fc1c149...|
+----------+-----------------+-----------------+-------------------+--------------------+--------------------+

Describing history for silver.location:

In [8]:

deltaTable = DeltaTable.forPath(spark, "silver\\location")
fullHistoryDF = deltaTable.history()
fullHistoryDF.show(truncate=False)

+-------+-----------------------+------+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+--------+---------+-----------+-----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-----------------------------------+
|version|timestamp              |userId|userName|operation   |operationParameters                                                                                                                                                                              |job |notebook|clusterId|readVersion|isolationLevel   |isBlindAppend|operationMetrics                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |userMetadata|engineInfo                         |
+-------+-----------------------+------+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+--------+---------+-----------+-----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-----------------------------------+
|4      |2024-10-13 19:45:06.497|NULL  |NULL    |MERGE       |{predicate -> ["(record_hash#11327 = record_hash#11285)"], matchedPredicates -> [{"actionType":"update"}], notMatchedPredicates -> [{"actionType":"insert"}], notMatchedBySourcePredicates -> []}|NULL|NULL    |NULL     |3          |Serializable     |false        |{numTargetRowsCopied -> 0, numTargetRowsDeleted -> 0, numTargetFilesAdded -> 13, numTargetBytesAdded -> 72978971, numTargetBytesRemoved -> 77200368, numTargetDeletionVectorsAdded -> 0, numTargetRowsMatchedUpdated -> 1006477, executionTimeMs -> 15951, numTargetRowsInserted -> 0, numTargetRowsMatchedDeleted -> 0, numTargetDeletionVectorsUpdated -> 0, scanTimeMs -> 6641, numTargetRowsUpdated -> 1006477, numOutputRows -> 1006477, numTargetDeletionVectorsRemoved -> 0, numTargetRowsNotMatchedBySourceUpdated -> 0, numTargetChangeFilesAdded -> 0, numSourceRows -> 1006477, numTargetFilesRemoved -> 12, numTargetRowsNotMatchedBySourceDeleted -> 0, rewriteTimeMs -> 4818}|NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|3      |2024-10-13 13:36:52.034|NULL  |NULL    |WRITE       |{mode -> Overwrite, partitionBy -> []}                                                                                                                                                           |NULL|NULL    |NULL     |2          |Serializable     |false        |{numFiles -> 12, numOutputRows -> 1006477, numOutputBytes -> 77200368}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|2      |2024-10-13 13:29:15.003|NULL  |NULL    |VACUUM END  |{status -> COMPLETED}                                                                                                                                                                            |NULL|NULL    |NULL     |1          |SnapshotIsolation|true         |{numDeletedFiles -> 0, numVacuumedDirectories -> 1}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|1      |2024-10-13 13:29:13.476|NULL  |NULL    |VACUUM START|{retentionCheckEnabled -> true, defaultRetentionMillis -> 604800000}                                                                                                                             |NULL|NULL    |NULL     |0          |SnapshotIsolation|true         |{numFilesToDelete -> 0, sizeOfDataToDelete -> 0}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|0      |2024-10-13 13:28:24.986|NULL  |NULL    |WRITE       |{mode -> Overwrite, partitionBy -> []}                                                                                                                                                           |NULL|NULL    |NULL     |NULL       |Serializable     |false        |{numFiles -> 12, numOutputRows -> 1006477, numOutputBytes -> 77200368}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
+-------+-----------------------+------+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----+--------+---------+-----------+-----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-----------------------------------+

In [9]:
dim_date = "gold.DIM_DATES"
dim_user = "gold.DIM_USERS"
dim_vehicle = "gold.DIM_VEHICLES"
dim_location = "gold.DIM_LOCATIONS"
fact_request = "gold.FCT_REQUESTS"

In [10]:
from pyspark.sql.functions import to_date, current_date

# Read data from each table and assign to individual variables
user_df = spark.read.table("silver.user").filter(to_date("processing_date") == current_date())
location_df = spark.read.table("silver.location").filter(to_date("processing_date") == current_date())
payment_df = spark.read.table("silver.payment").filter(to_date("processing_date") == current_date())
paymentmethod_df = spark.read.table("silver.payment_method").filter(to_date("processing_date") == current_date())
paymentstatus_df = spark.read.table("silver.payment_status").filter(to_date("processing_date") == current_date())
request_df = spark.read.table("silver.request").filter(to_date("processing_date") == current_date())
trip_df = spark.read.table("silver.trip").filter(to_date("processing_date") == current_date())
vehicle_df = spark.read.table("silver.vehicle").filter(to_date("processing_date") == current_date())
vehiclemake_df = spark.read.table("silver.vehicle_make").filter(to_date("processing_date") == current_date())

# Show each DataFrame separately
user_df.show()
location_df.show()
payment_df.show()
paymentmethod_df.show()
paymentstatus_df.show()
request_df.show()
trip_df.show()
vehicle_df.show()
vehiclemake_df.show()

+-------+---------------+--------------------+--------------+-------------------+--------------------+--------------------+
|user_id|      full_name|               email|  phone_number|    processing_date|record_modified_date|         record_hash|
+-------+---------------+--------------------+--------------+-------------------+--------------------+--------------------+
|  21485| Anthony Morgan|ubradford@example...|(175) 891-4063|2024-10-13 19:44:31|2024-10-13 13:07:...|000082258f3c61f26...|
|1017693|  Jesse Gregory|garyrodriguez@exa...|(806) 231-5009|2024-10-13 19:44:31|2024-10-13 13:07:...|00009d1306f8d0d7e...|
|1174541|  Michael Davis|reyesdaniel@examp...|(724) 952-2855|2024-10-13 19:44:31|2024-10-13 13:34:...|00019ce038354f826...|
| 986574|Haley Alexander|joannejohnson@exa...|(606) 214-3136|2024-10-13 19:44:31|2024-10-13 13:34:...|0001d7e8506472aab...|
|1014405|   Lori Trevino|laurenrobbins@exa...|(393) 778-7835|2024-10-13 19:44:31|2024-10-13 13:34:...|000554497b1fe9ec8...|
| 108642|Jade Williamson| zvaldez@example.net|(384) 258-9520|2024-10-13 19:44:31|2024-10-13 13:34:...|00057c4933172603e...|
|  34902|    Brett Moore|kristen20@example...|(479) 843-5980|2024-10-13 19:44:31|2024-10-13 13:07:...|0005b9cd3e528e3ac...|
| 950402|    Jose Parker|jeanneguerra@exam...|(461) 939-1802|2024-10-13 19:44:31|2024-10-13 13:34:...|0007aa0d0e52929d2...|
| 997367|   Robert Young|brittanypalmer@ex...|(521) 171-7367|2024-10-13 19:44:31|2024-10-13 13:34:...|000941df48431d700...|
|1093225|Margaret Atkins|smithhannah@examp...|(637) 725-2191|2024-10-13 19:44:31|2024-10-13 13:07:...|000b0978cab8a01a0...|
|  18715|    Anita White|ysampson@example.com|(168) 632-3294|2024-10-13 19:44:31|2024-10-13 13:07:...|000cbd5ea133cdd95...|
| 213882|     Nancy Cook| ithomas@example.net|(533) 983-4507|2024-10-13 19:44:31|2024-10-13 13:07:...|000d167021128a416...|
| 256793|    Shelby Mays|alvaradojennifer@...|(467) 142-3257|2024-10-13 19:44:31|2024-10-13 13:34:...|000d375211abc67ac...|
|1061460|  Rachael Cohen|michaelmoyer@exam...|(783) 247-8224|2024-10-13 19:44:31|2024-10-13 13:07:...|0010945ccd0c7f8eb...|
| 201851| Michael Nelson|steven22@example.org|(595) 387-9944|2024-10-13 19:44:31|2024-10-13 13:07:...|001244c8e0069f344...|
| 985867|    Kim Stanley|patrick85@example...|(946) 752-8395|2024-10-13 19:44:31|2024-10-13 13:34:...|00146cc7b6cbeb5e4...|
| 991736|    Jill Barton|xjackson@example.org|(562) 220-1092|2024-10-13 19:44:31|2024-10-13 13:34:...|0014c1d6ea5562718...|
| 833285|      Eric Pham|gregory26@example...|(763) 607-1886|2024-10-13 19:44:31|2024-10-13 13:07:...|00157077ab733549a...|
| 813872|     Adam Dixon|   rwood@example.net|(744) 622-3884|2024-10-13 19:44:31|2024-10-13 13:07:...|001603cc55e2ae68f...|
| 859065|   Debra Harris|nhernandez@exampl...|(682) 348-6831|2024-10-13 19:44:31|2024-10-13 13:07:...|0016b8eb82c3dcb3e...|
+-------+---------------+--------------------+--------------+-------------------+--------------------+--------------------+
only showing top 20 rows

+-----------+------------+-----------+-------------------+--------------------+--------------------+
|location_id|   longitude|   latitude|    processing_date|record_modified_date|         record_hash|
+-----------+------------+-----------+-------------------+--------------------+--------------------+
|     140808|-73.99198151|40.74440384|2024-10-13 19:44:50|2024-10-08 09:46:...|000205e54ddf8bc75...|
|    1099001|-73.98711395|40.72247696|2024-10-13 19:44:50|2024-10-08 09:46:...|000269e922cb80d92...|
|     419142|-73.96898651|40.75440979|2024-10-13 19:44:50|2024-10-08 09:46:...|0003b97e281e1e707...|
|     405519| -73.9709549|40.76442337|2024-10-13 19:44:50|2024-10-08 09:46:...|000409aca98f097ad...|
|     428147|-73.96775818|40.75773621|2024-10-13 19:44:50|2024-10-08 09:46:...|00042377f909c5272...|
|     232211|-73.98554993|40.74724197|2024-10-13 19:44:50|2024-10-08 09:46:...|0006381378d59db98...|
|    1435854|-73.96662903|40.76414871|2024-10-13 19:44:50|2024-10-08 09:46:...|0006a102f7b890845...|
|    1024948|-73.98249054|40.73995972|2024-10-13 19:44:50|2024-10-08 09:46:...|00073e2b7c177c101...|
|    1601613|-73.96591949|40.75263977|2024-10-13 19:44:50|2024-10-08 09:46:...|0008619dfbe813c46...|
|    1100722| -73.9495163|40.77864838|2024-10-13 19:44:50|2024-10-08 09:46:...|000a4c38f7eb929b3...|
|     564879|-73.78232574|40.64452744|2024-10-13 19:44:50|2024-10-08 09:46:...|000c62c80a97e67bd...|
|     963528|-73.95597839| 40.6946106|2024-10-13 19:44:50|2024-10-08 09:46:...|000e36608c629f765...|
|     496545|-73.95554352|40.77680206|2024-10-13 19:44:50|2024-10-08 09:46:...|000f5ce2248227996...|
|     300123|-73.98092651|40.76207352|2024-10-13 19:44:50|2024-10-08 09:46:...|00101454767b15db9...|
|    1216556|  -73.961586|40.75581741|2024-10-13 19:44:50|2024-10-08 09:46:...|001293a0ba2e80f1a...|
|    1120793|-73.98009491|40.75146103|2024-10-13 19:44:50|2024-10-08 09:46:...|001335c79fa85073c...|
|     163818|-73.99047852|40.75507355|2024-10-13 19:44:50|2024-10-08 09:46:...|0013acdce600055ef...|
|       8554|-74.01144409|40.70281219|2024-10-13 19:44:50|2024-10-08 09:46:...|0013fa1710b8b0e48...|
|    1682356|-73.95649719|40.77541351|2024-10-13 19:44:50|2024-10-08 09:46:...|00156b16f941e43b5...|
|     543786|-73.92095947|40.76676178|2024-10-13 19:44:50|2024-10-08 09:46:...|001691fa79e420185...|
+-----------+------------+-----------+-------------------+--------------------+--------------------+
only showing top 20 rows

+----------+-----------------+-----------------+-------------------+--------------------+--------------------+
|payment_id|payment_method_id|payment_status_id|    processing_date|record_modified_date|         record_hash|
+----------+-----------------+-----------------+-------------------+--------------------+--------------------+
|      NULL|             NULL|             NULL|2024-10-13 19:45:08|2024-10-08 09:47:...|e3b0c44298fc1c149...|
|         1|                1|                1|2024-10-13 19:45:08|2024-10-08 09:47:...|6b86b273ff34fce19...|
|         6|                6|                4|2024-10-13 19:45:08|2024-10-08 09:47:...|e7f6c011776e8db7c...|
|         3|                3|                1|2024-10-13 19:45:08|2024-10-08 09:47:...|4e07408562bedb8b6...|
|         5|                5|                2|2024-10-13 19:45:08|2024-10-08 09:47:...|ef2d127de37b942ba...|
|         4|                4|                4|2024-10-13 19:45:08|2024-10-08 09:47:...|4b227777d4dd1fc61...|
|         2|                2|                3|2024-10-13 19:45:08|2024-10-08 09:47:...|d4735e3a265e16eee...|
+----------+-----------------+-----------------+-------------------+--------------------+--------------------+

+-----------------+-----------+-------------------+--------------------+--------------------+
|payment_method_id|method_name|    processing_date|record_modified_date|         record_hash|
+-----------------+-----------+-------------------+--------------------+--------------------+
|             NULL| ----------|2024-10-13 19:45:10|2024-10-08 09:47:...|e3b0c44298fc1c149...|
|                1|  Apple Pay|2024-10-13 19:45:10|2024-10-08 09:47:...|6b86b273ff34fce19...|
|                2|       Cash|2024-10-13 19:45:10|2024-10-08 09:47:...|d4735e3a265e16eee...|
|                3|Credit Card|2024-10-13 19:45:10|2024-10-08 09:47:...|4e07408562bedb8b6...|
|                4| Debit Card|2024-10-13 19:45:10|2024-10-08 09:47:...|4b227777d4dd1fc61...|
|                5| Google Pay|2024-10-13 19:45:10|2024-10-08 09:47:...|ef2d127de37b942ba...|
|                6|     PayPal|2024-10-13 19:45:10|2024-10-08 09:47:...|e7f6c011776e8db7c...|
+-----------------+-----------+-------------------+--------------------+--------------------+

+-----------------+-----------+-------------------+--------------------+--------------------+
|payment_status_id|status_name|    processing_date|record_modified_date|         record_hash|
+-----------------+-----------+-------------------+--------------------+--------------------+
|             NULL| ----------|2024-10-13 19:45:13|2024-10-08 09:47:...|e3b0c44298fc1c149...|
|                1|  Completed|2024-10-13 19:45:13|2024-10-08 09:47:...|6b86b273ff34fce19...|
|                2|     Failed|2024-10-13 19:45:13|2024-10-08 09:47:...|d4735e3a265e16eee...|
|                3|    Pending|2024-10-13 19:45:13|2024-10-08 09:47:...|4e07408562bedb8b6...|
|                4|   Refunded|2024-10-13 19:45:13|2024-10-08 09:47:...|4b227777d4dd1fc61...|
+-----------------+-----------+-------------------+--------------------+--------------------+

+----------+------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+
|request_id|passenger_id|pickup_location_id|dropoff_location_id|       request_time|        accept_time|    processing_date|record_modified_date|         record_hash|
+----------+------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+
|    447450|      224189|            376530|             338646|2015-01-04 15:28:00|2015-01-04 15:30:00|2024-10-13 19:45:15|2024-10-08 09:47:...|02018d1c2a52d91dd...|
|    433893|      217445|            562731|             567647|2015-01-29 12:34:00|2015-01-29 12:44:00|2024-10-13 19:45:15|2024-10-08 09:47:...|eef0dbb103d3fbc24...|
|    178990|       88035|            544948|             513195|2015-01-30 17:50:00|2015-01-30 17:51:00|2024-10-13 19:45:15|2024-10-08 09:47:...|536eeb49f7dca596d...|
|    379467|      189160|            500234|             377330|2015-01-22 17:42:00|2015-01-22 17:49:00|2024-10-13 19:45:15|2024-10-08 09:47:...|abc91cee122aad675...|
|    542452|      271225|            221413|             555053|2015-01-19 03:17:00|2015-01-19 03:21:00|2024-10-13 19:45:15|2024-10-08 09:47:...|c6913cfeb8c196e6c...|
|    378078|      188332|            233084|              52708|2015-01-13 08:16:00|2015-01-13 08:19:00|2024-10-13 19:45:15|2024-10-08 09:47:...|2470291627a22640c...|
|    580109|      289762|             53325|             245154|2015-01-23 18:38:00|2015-01-23 18:45:00|2024-10-13 19:45:15|2024-10-08 09:47:...|c712af7249177a22d...|
|     68927|       34073|            546585|             190100|2015-01-21 21:42:00|2015-01-21 21:46:00|2024-10-13 19:45:15|2024-10-08 09:47:...|63fafbc9f67582da4...|
|      8546|        4036|            297217|             272753|2015-01-28 07:39:00|2015-01-28 07:45:00|2024-10-13 19:45:15|2024-10-08 09:47:...|8430d37ddd0a8b36b...|
|    186073|       91722|            172150|             233498|2015-01-22 18:45:00|2015-01-22 18:49:00|2024-10-13 19:45:15|2024-10-08 09:47:...|cf17c8a59b2a24375...|
|    251416|      124593|             76826|             251958|2015-01-05 23:00:00|2015-01-05 23:10:00|2024-10-13 19:45:15|2024-10-08 09:47:...|95a6442234ed05a0b...|
|    110740|       54422|            233662|             154584|2015-01-07 11:57:00|2015-01-07 11:59:00|2024-10-13 19:45:15|2024-10-08 09:47:...|0a3c23c70b4750c6e...|
|    283433|      141459|             46488|              77632|2015-01-14 16:12:00|2015-01-14 16:14:00|2024-10-13 19:45:15|2024-10-08 09:47:...|7d03c8f9bd3e8d8f8...|
|     78641|       39014|            146777|             203738|2015-01-22 15:06:00|2015-01-22 15:09:00|2024-10-13 19:45:15|2024-10-08 09:47:...|19c2fd695d2f1069a...|
|    151863|       75582|             78275|             143275|2015-01-17 23:05:00|2015-01-17 23:14:00|2024-10-13 19:45:15|2024-10-08 09:47:...|6c61916eaa94e6f75...|
|    281266|      140337|            362986|             428790|2015-01-11 11:44:00|2015-01-11 11:52:00|2024-10-13 19:45:15|2024-10-08 09:47:...|780a7cfa1ed0d3264...|
|    197514|       96928|            293946|             182144|2015-01-15 18:44:00|2015-01-15 18:49:00|2024-10-13 19:45:15|2024-10-08 09:47:...|7d9ece0abbf066901...|
|    111424|       54820|            252399|             341953|2015-01-23 13:26:00|2015-01-23 13:28:00|2024-10-13 19:45:15|2024-10-08 09:47:...|d95626d9bf24597e6...|
|    303704|      151871|             24459|             203618|2015-01-22 20:35:00|2015-01-22 20:37:00|2024-10-13 19:45:15|2024-10-08 09:47:...|fe8564616fbc13390...|
|    506606|      253910|            378025|             338504|2015-01-20 16:02:00|2015-01-20 16:09:00|2024-10-13 19:45:15|2024-10-08 09:47:...|585d9765f8dd5b07e...|
+----------+------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+
only showing top 20 rows

+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
|trip_id|request_id|driver_id|vehicle_id|payment_id|    trip_start_time|      trip_end_time|trip_distance|base_fare|extra_fare|mta_tax|tip_amount|tolls_amount|improvement_surcharge|    processing_date|record_modified_date|         record_hash|
+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
|  52273|    387479|  1133778|    241226|         6|2015-01-06 08:17:00|2015-01-06 08:21:00|         0.57|      4.5|       0.0|    0.5|      1.35|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|55eac87a0175d172d...|
|  52513|    304466|  1071291|     75238|         4|2015-01-09 12:50:00|2015-01-09 12:54:00|         0.59|      4.5|       0.0|    0.5|      1.12|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|05cbe877f3906106f...|
|  52972|    245931|   852437|     14760|         5|2015-01-05 09:50:00|2015-01-05 10:02:00|         0.93|      9.0|       0.0|    0.5|       1.8|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|62548ea3a4073f729...|
|  53208|     42995|  1011310|    365818|         1|2015-01-01 07:26:00|2015-01-01 07:37:00|          3.0|     11.5|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|8d145f20fdc0b771c...|
|  53282|    413323|  1032813|    114089|         6|2015-01-04 00:17:00|2015-01-04 00:25:00|          1.5|      8.0|       0.5|    0.5|       1.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|78e5c0b3811b92585...|
|  53495|    161809|   782193|    157183|         2|2015-01-30 13:39:00|2015-01-30 13:54:00|          1.6|     11.0|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|adf38727653d50e8d...|
|  53621|    279415|  1088014|      8655|         5|2015-01-04 01:12:00|2015-01-04 01:29:00|         3.27|     14.0|       0.5|    0.5|       2.9|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|21eb2cbe65b5ed4d3...|
|  53622|    116098|   972558|    187409|         4|2015-01-04 01:12:00|2015-01-04 01:21:00|         1.93|      8.5|       0.5|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|32402830a3d32ecf6...|
|  54210|    459025|  1102298|    165269|         4|2015-01-08 07:55:00|2015-01-08 08:03:00|          1.0|      7.0|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|7868cc939dca082fd...|
|  54285|    114521|  1038363|     71464|         6|2015-01-15 09:04:00|2015-01-15 09:32:00|         4.29|     20.5|       0.0|    0.5|       4.1|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|c62460e4091ed590a...|
|  54539|    352645|  1050452|    204616|         3|2015-01-29 14:01:00|2015-01-29 14:08:00|         0.74|      6.0|       0.0|    0.5|       1.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|802bd6e9e42cd7f53...|
|  54993|      4415|   955995|     38381|         3|2015-01-03 09:19:00|2015-01-03 09:33:00|          2.8|     12.5|       0.0|    0.5|       0.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|cb4fd712fd2fe08bb...|
|  55078|    142419|   840739|    100485|         5|2015-01-05 17:25:00|2015-01-05 17:36:00|         1.41|      9.0|       1.0|    0.5|       1.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|f93bbb9c17a1d196a...|
|  55106|    369660|   934532|    304977|         3|2015-01-04 08:11:00|2015-01-04 08:15:00|          1.3|      6.0|       0.0|    0.5|       0.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|9cc7392e805100299...|
|  55206|    278277|  1093847|    370784|         6|2015-01-04 08:51:00|2015-01-04 08:54:00|          0.6|      4.5|       0.0|    0.5|       0.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|a91b2c2d640b3c037...|
|  55815|    223062|   984862|    174006|         6|2015-01-10 18:49:00|2015-01-10 19:05:00|         2.17|     12.0|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|0d1f163146deb35a8...|
|  55870|    249870|   910307|    121943|         5|2015-01-10 22:14:00|2015-01-10 22:17:00|          0.3|      3.5|       0.5|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|dfcd3e1f86d99e6cd...|
|  55896|     17990|   861203|    316846|         5|2015-01-18 12:20:00|2015-01-18 12:36:00|         3.92|     14.5|       0.0|    0.5|       2.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|b909eac423130416f...|
|  56020|    106007|   828991|    351557|         1|2015-01-30 14:30:00|2015-01-30 14:38:00|          0.6|      6.5|       0.0|    0.5|      1.45|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|9cc285bbe80d69e2f...|
|  56314|    138783|   837824|    364297|         2|2015-01-16 17:52:00|2015-01-16 17:55:00|         0.42|      4.5|       1.0|    0.5|       0.7|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|9a75bba4a6dd73833...|
+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
only showing top 20 rows

+----------+---------+-------+---------+----+------+-------------+-------------------+--------------------+--------------------+
|vehicle_id|driver_id|make_id|    model|year| color|license_plate|    processing_date|record_modified_date|         record_hash|
+----------+---------+-------+---------+----+------+-------------+-------------------+--------------------+--------------------+
|    346451|   929946|     10|     Golf|2012|   Red|      048 GMJ|2024-10-13 19:45:28|2024-10-08 09:46:...|000159a479a5979a4...|
|    190744|   885213|      6|    Forte|1993|Silver|      RA1 C4G|2024-10-13 19:45:28|2024-10-08 09:46:...|000219a26b647ac79...|
|    151239|  1119944|      5|  Elantra|1994| Green|      HVD 637|2024-10-13 19:45:28|2024-10-08 09:46:...|00062c9861781769d...|
|    172693|  1025732|      5|   Sonata|1995|  Gray|      058-DRS|2024-10-13 19:45:28|2024-10-08 09:46:...|0008a608d72e2e651...|
|     68974|  1012331|      2|    Tahoe|2021| Brown|      707-RKC|2024-10-13 19:45:28|2024-10-08 09:46:...|0009cec48d4ef3f26...|
|    225644|   840959|      7|  C-Class|2011| Green|      QO 0906|2024-10-13 19:45:28|2024-10-08 09:46:...|000c89a0f40266ec0...|
|    368118|   964862|     10|   Tiguan|1997|   Red|         608D|2024-10-13 19:45:28|2024-10-08 09:46:...|00121e286ea9a3d3c...|
|    311446|   878179|      9|  Corolla|2016|Yellow|      172-HPR|2024-10-13 19:45:28|2024-10-08 09:46:...|0012bc466fb6dda21...|

In [11]:
user_df.orderBy("full_name").show()

+-------+------------+--------------------+--------------+-------------------+--------------------+--------------------+
|user_id|   full_name|               email|  phone_number|    processing_date|record_modified_date|         record_hash|
+-------+------------+--------------------+--------------+-------------------+--------------------+--------------------+
|   NULL|    --------|               -----|   -----------|2024-10-13 19:44:31|2024-10-13 13:07:...|370d9b71060be968d...|
| 768128|Aaron Abbott|angela67@example.com|(453) 832-3608|2024-10-13 19:44:31|2024-10-13 13:34:...|1ec48e73a3376b697...|
| 762535|Aaron Abbott|angela67@example.com|(453) 832-3608|2024-10-13 19:44:31|2024-10-13 13:34:...|7c4dfcfb597e8c6e2...|
| 767104|Aaron Abbott|angela67@example.com|(453) 832-3608|2024-10-13 19:44:31|2024-10-13 13:34:...|24d00ea8fc1be35ea...|
| 776168|Aaron Abbott|angela67@example.com|(453) 832-3608|2024-10-13 19:44:31|2024-10-13 13:34:...|408174e83dc4afa4d...|
| 967068|Aaron Acosta|vanessa20@example...|(953) 599-6007|2024-10-13 19:44:31|2024-10-13 13:34:...|c4f5b7dba1250f9c8...|
|      1|Aaron Acosta| account@example.net|(677) 367-9557|2024-10-13 19:44:31|2024-10-13 13:07:...|21d31195f82942e05...|
| 850461|Aaron Acosta|vanessa20@example...|(953) 599-6007|2024-10-13 19:44:31|2024-10-13 13:07:...|9ffbb377c4a47210a...|
| 869145| Aaron Adams|jesseschwartz@exa...|(250) 242-4652|2024-10-13 19:44:31|2024-10-13 13:07:...|092f7cfb9a2639ccc...|
| 958105| Aaron Adams|angela64@example.com|(619) 154-2732|2024-10-13 19:44:31|2024-10-13 13:34:...|83ff9b2d18d1e9ad9...|
|      3| Aaron Adams|monopoly@example.net|(351) 943-8670|2024-10-13 19:44:31|2024-10-13 13:07:...|500bf842d2becc183...|
|      4| Aaron Adams|zjohnson@example.com|(324) 384-5822|2024-10-13 19:44:31|2024-10-13 13:07:...|60f62b9afaac9bbb8...|
| 795166| Aaron Adams|  dbowen@example.net|(672) 995-6696|2024-10-13 19:44:31|2024-10-13 13:07:...|f6a334f710dd054e2...|
| 787488| Aaron Adams|  dbowen@example.net|(672) 995-6696|2024-10-13 19:44:31|2024-10-13 13:07:...|d23e37fd512811dcd...|
| 755043| Aaron Adams|beckdaniel@exampl...|(987) 878-1073|2024-10-13 19:44:31|2024-10-13 13:34:...|f37af311dc85681be...|
|      2| Aaron Adams| james82@example.com|(332) 224-7965|2024-10-13 19:44:31|2024-10-13 13:07:...|683e6c22fa1e45bef...|
| 916376| Aaron Adams|  jill51@example.org|(120) 200-5627|2024-10-13 19:44:31|2024-10-13 13:34:...|b8b13cd2f9d2014f2...|
| 757174| Aaron Adams|  dbowen@example.net|(672) 995-6696|2024-10-13 19:44:31|2024-10-13 13:34:...|d0f0642915afc8d9d...|
| 758776| Aaron Adams|  dbowen@example.net|(672) 995-6696|2024-10-13 19:44:31|2024-10-13 13:34:...|19adffa1d192cbeb1...|
| 934434| Aaron Adams| emily69@example.net|(217) 156-8782|2024-10-13 19:44:31|2024-10-13 13:34:...|eb653d2a538d2ece4...|
+-------+------------+--------------------+--------------+-------------------+--------------------+--------------------+
only showing top 20 rows

In [12]:
# Step 1: Join user_df with vehicle_df on user_id (assuming driver_id in vehicle_df relates to user_id)
user_vehicle_df = user_df.join(vehicle_df, user_df["user_id"] == vehicle_df["driver_id"], "left")

# Step 2: Join vehicle_df with vehicle_make_df on make_id to bring in make details
user_vehicle_make_df = user_vehicle_df.join(vehiclemake_df, vehicle_df["make_id"] == vehiclemake_df["make_id"], "left")

In [13]:
dim_user = user_vehicle_make_df.select(
    "user_id",
    "full_name",
    "email",
    "phone_number",
    # Replace NULLs in vehicle columns with 'Passenger' or 'N/A'
    coalesce(user_vehicle_make_df["vehicle_id"], lit("Passenger")).alias("vehicle_id"),
    coalesce(user_vehicle_make_df["make_name"], lit("Passenger")).alias("vehicle_make"),
    coalesce(user_vehicle_make_df["model"], lit("Passenger")).alias("vehicle_model"),
    coalesce(user_vehicle_make_df["year"], lit("Passenger")).alias("vehicle_year"),
    coalesce(user_vehicle_make_df["color"], lit("Passenger")).alias("vehicle_color"),
    coalesce(user_vehicle_make_df["license_plate"], lit("Passenger")).alias("vehicle_license_plate")
)

In [14]:
dim_user.orderBy("full_name").show()

+-------+------------+--------------------+--------------+----------+------------+-------------+------------+-------------+---------------------+
|user_id|   full_name|               email|  phone_number|vehicle_id|vehicle_make|vehicle_model|vehicle_year|vehicle_color|vehicle_license_plate|
+-------+------------+--------------------+--------------+----------+------------+-------------+------------+-------------+---------------------+
|   NULL|    --------|               -----|   -----------| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|
| 762535|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|
| 768128|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|
| 776168|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|
| 767104|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|
|      1|Aaron Acosta| account@example.net|(677) 367-9557| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|
| 850461|Aaron Acosta|vanessa20@example...|(953) 599-6007|     11618|         BMW|     5 Series|        2017|       Orange|                 389J|
| 967068|Aaron Acosta|vanessa20@example...|(953) 599-6007|     11618|         BMW|     5 Series|        2017|       Orange|                 389J|
|      3| Aaron Adams|monopoly@example.net|(351) 943-8670| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|
| 755043| Aaron Adams|beckdaniel@exampl...|(987) 878-1073|     52562|   Chevrolet|       Malibu|        2022|        Black|              324 JEN|
| 916376| Aaron Adams|  jill51@example.org|(120) 200-5627|    138962|       Honda|          Fit|        2006|       Silver|              65M 278|
| 787488| Aaron Adams|  dbowen@example.net|(672) 995-6696|     23039|         BMW|           X5|        1996|         Blue|              IIV-491|
| 957585| Aaron Adams|beckdaniel@exampl...|(987) 878-1073|     52562|   Chevrolet|       Malibu|        2022|        Black|              324 JEN|
|      4| Aaron Adams|zjohnson@example.com|(324) 384-5822| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|
| 757174| Aaron Adams|  dbowen@example.net|(672) 995-6696|     23039|         BMW|           X5|        1996|         Blue|              IIV-491|
| 758776| Aaron Adams|  dbowen@example.net|(672) 995-6696|     75956|        Ford|       Escape|        1996|        Brown|                3G783|
| 934434| Aaron Adams| emily69@example.net|(217) 156-8782|     67661|   Chevrolet|        Tahoe|        1994|         Blue|              YCF 385|
|      2| Aaron Adams| james82@example.com|(332) 224-7965| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|
| 795166| Aaron Adams|  dbowen@example.net|(672) 995-6696|     74881|        Ford|       Escape|        2017|        Black|              0BUG 39|
| 958105| Aaron Adams|angela64@example.com|(619) 154-2732|     27003|         BMW|           X5|        2006|          Red|              NFD-596|
+-------+------------+--------------------+--------------+----------+------------+-------------+------------+-------------+---------------------+
only showing top 20 rows

In [15]:

# Define the start and end date
start_date = "2015-01-01"
end_date = "2015-01-31"

# Create a Spark DataFrame with a date range using the sequence function
calendar_df = spark.sql(f"""
    SELECT explode(sequence(to_date('{start_date}'), to_date('{end_date}'), interval 1 day)) as full_date
""")

# Transform the DataFrame to create the calendar dimension
dim_calendar = calendar_df.select(
    date_format("full_date", "yyyyMMdd").alias("date_key"),  # Convert to string format YYYYMMDD
    col("full_date"),
    dayofmonth("full_date").alias("day"),  # Day of the month
    date_format("full_date", "EEEE").alias("day_name"),  # Full name of the day
    dayofweek("full_date").alias("day_of_week"),  # Day of the week (1 = Sunday, 7 = Saturday)
    weekofyear("full_date").alias("week_of_year"),  # Week of the year
    month("full_date").alias("month"),  # Month (1-12)
    date_format("full_date", "MMMM").alias("month_name"),  # Full name of the month
    quarter("full_date").alias("quarter"),  # Quarter (1-4)
    year("full_date").alias("year"),  # Year
    when(dayofweek("full_date").isin([1, 7]), 1).otherwise(0).alias("is_weekend"),  # Weekend flag (1=weekend)
    lit(0).alias("is_holiday"),  # Dummy holiday flag (replace with actual holiday logic)
    month("full_date").alias("fiscal_month"),  # Fiscal month (you can customize this logic)
    quarter("full_date").alias("fiscal_quarter"),  # Fiscal quarter (you can customize this logic)
    year("full_date").alias("fiscal_year")  # Fiscal year
)

dim_calendar.printSchema()
# Show the resulting calendar dimension DataFrame

root
 |-- date_key: string (nullable = false)
 |-- full_date: date (nullable = false)
 |-- day: integer (nullable = false)
 |-- day_name: string (nullable = false)
 |-- day_of_week: integer (nullable = false)
 |-- week_of_year: integer (nullable = false)
 |-- month: integer (nullable = false)
 |-- month_name: string (nullable = false)
 |-- quarter: integer (nullable = false)
 |-- year: integer (nullable = false)
 |-- is_weekend: integer (nullable = false)
 |-- is_holiday: integer (nullable = false)
 |-- fiscal_month: integer (nullable = false)
 |-- fiscal_quarter: integer (nullable = false)
 |-- fiscal_year: integer (nullable = false)

In [16]:
dim_calendar.show(8)

+--------+----------+---+---------+-----------+------------+-----+----------+-------+----+----------+----------+------------+--------------+-----------+
|date_key| full_date|day| day_name|day_of_week|week_of_year|month|month_name|quarter|year|is_weekend|is_holiday|fiscal_month|fiscal_quarter|fiscal_year|
+--------+----------+---+---------+-----------+------------+-----+----------+-------+----+----------+----------+------------+--------------+-----------+
|20150101|2015-01-01|  1| Thursday|          5|           1|    1|   January|      1|2015|         0|         0|           1|             1|       2015|
|20150102|2015-01-02|  2|   Friday|          6|           1|    1|   January|      1|2015|         0|         0|           1|             1|       2015|
|20150103|2015-01-03|  3| Saturday|          7|           1|    1|   January|      1|2015|         1|         0|           1|             1|       2015|
|20150104|2015-01-04|  4|   Sunday|          1|           1|    1|   January|      1|2015|         1|         0|           1|             1|       2015|
|20150105|2015-01-05|  5|   Monday|          2|           2|    1|   January|      1|2015|         0|         0|           1|             1|       2015|
|20150106|2015-01-06|  6|  Tuesday|          3|           2|    1|   January|      1|2015|         0|         0|           1|             1|       2015|
|20150107|2015-01-07|  7|Wednesday|          4|           2|    1|   January|      1|2015|         0|         0|           1|             1|       2015|
|20150108|2015-01-08|  8| Thursday|          5|           2|    1|   January|      1|2015|         0|         0|           1|             1|       2015|
+--------+----------+---+---------+-----------+------------+-----+----------+-------+----+----------+----------+------------+--------------+-----------+
only showing top 8 rows

In [17]:
paymentmethod_df.show()
paymentstatus_df.show()

+-----------------+-----------+-------------------+--------------------+--------------------+
|payment_method_id|method_name|    processing_date|record_modified_date|         record_hash|
+-----------------+-----------+-------------------+--------------------+--------------------+
|             NULL| ----------|2024-10-13 19:45:10|2024-10-08 09:47:...|e3b0c44298fc1c149...|
|                1|  Apple Pay|2024-10-13 19:45:10|2024-10-08 09:47:...|6b86b273ff34fce19...|
|                2|       Cash|2024-10-13 19:45:10|2024-10-08 09:47:...|d4735e3a265e16eee...|
|                3|Credit Card|2024-10-13 19:45:10|2024-10-08 09:47:...|4e07408562bedb8b6...|
|                4| Debit Card|2024-10-13 19:45:10|2024-10-08 09:47:...|4b227777d4dd1fc61...|
|                5| Google Pay|2024-10-13 19:45:10|2024-10-08 09:47:...|ef2d127de37b942ba...|
|                6|     PayPal|2024-10-13 19:45:10|2024-10-08 09:47:...|e7f6c011776e8db7c...|
+-----------------+-----------+-------------------+--------------------+--------------------+

+-----------------+-----------+-------------------+--------------------+--------------------+
|payment_status_id|status_name|    processing_date|record_modified_date|         record_hash|
+-----------------+-----------+-------------------+--------------------+--------------------+
|             NULL| ----------|2024-10-13 19:45:13|2024-10-08 09:47:...|e3b0c44298fc1c149...|
|                1|  Completed|2024-10-13 19:45:13|2024-10-08 09:47:...|6b86b273ff34fce19...|
|                2|     Failed|2024-10-13 19:45:13|2024-10-08 09:47:...|d4735e3a265e16eee...|
|                3|    Pending|2024-10-13 19:45:13|2024-10-08 09:47:...|4e07408562bedb8b6...|
|                4|   Refunded|2024-10-13 19:45:13|2024-10-08 09:47:...|4b227777d4dd1fc61...|
+-----------------+-----------+-------------------+--------------------+--------------------+

In [18]:
# Perform a cross join to get all combinations of PaymentMethod and PaymentStatus
combined_df = paymentmethod_df.crossJoin(paymentstatus_df)

# Add an incremental surrogate key
final_df = combined_df.withColumn("s_payment", monotonically_increasing_id())

# Select only the relevant columns (SurrogateKey, PaymentMethodID, PaymentStatusID)
final_df = final_df.select("s_payment", "payment_method_id", "method_name", "payment_status_id", "status_name")

# Show the resulting DataFrame
final_df.show(30)

+---------+-----------------+-----------+-----------------+-----------+
|s_payment|payment_method_id|method_name|payment_status_id|status_name|
+---------+-----------------+-----------+-----------------+-----------+
|        0|             NULL| ----------|             NULL| ----------|
|        1|             NULL| ----------|                1|  Completed|
|        2|             NULL| ----------|                2|     Failed|
|        3|             NULL| ----------|                3|    Pending|
|        4|             NULL| ----------|                4|   Refunded|
|        5|                1|  Apple Pay|             NULL| ----------|
|        6|                1|  Apple Pay|                1|  Completed|
|        7|                1|  Apple Pay|                2|     Failed|
|        8|                1|  Apple Pay|                3|    Pending|
|        9|                1|  Apple Pay|                4|   Refunded|
|       10|                2|       Cash|             NULL| ----------|
|       11|                2|       Cash|                1|  Completed|
|       12|                2|       Cash|                2|     Failed|
|       13|                2|       Cash|                3|    Pending|
|       14|                2|       Cash|                4|   Refunded|
|       15|                3|Credit Card|             NULL| ----------|
|       16|                3|Credit Card|                1|  Completed|
|       17|                3|Credit Card|                2|     Failed|
|       18|                3|Credit Card|                3|    Pending|
|       19|                3|Credit Card|                4|   Refunded|
|       20|                4| Debit Card|             NULL| ----------|
|       21|                4| Debit Card|                1|  Completed|
|       22|                4| Debit Card|                2|     Failed|
|       23|                4| Debit Card|                3|    Pending|
|       24|                4| Debit Card|                4|   Refunded|
|       25|                5| Google Pay|             NULL| ----------|
|       26|                5| Google Pay|                1|  Completed|
|       27|                5| Google Pay|                2|     Failed|
|       28|                5| Google Pay|                3|    Pending|
|       29|                5| Google Pay|                4|   Refunded|
+---------+-----------------+-----------+-----------------+-----------+
only showing top 30 rows

In [19]:
payment_df.show()

+----------+-----------------+-----------------+-------------------+--------------------+--------------------+
|payment_id|payment_method_id|payment_status_id|    processing_date|record_modified_date|         record_hash|
+----------+-----------------+-----------------+-------------------+--------------------+--------------------+
|      NULL|             NULL|             NULL|2024-10-13 19:45:08|2024-10-08 09:47:...|e3b0c44298fc1c149...|
|         1|                1|                1|2024-10-13 19:45:08|2024-10-08 09:47:...|6b86b273ff34fce19...|
|         6|                6|                4|2024-10-13 19:45:08|2024-10-08 09:47:...|e7f6c011776e8db7c...|
|         3|                3|                1|2024-10-13 19:45:08|2024-10-08 09:47:...|4e07408562bedb8b6...|
|         5|                5|                2|2024-10-13 19:45:08|2024-10-08 09:47:...|ef2d127de37b942ba...|
|         4|                4|                4|2024-10-13 19:45:08|2024-10-08 09:47:...|4b227777d4dd1fc61...|
|         2|                2|                3|2024-10-13 19:45:08|2024-10-08 09:47:...|d4735e3a265e16eee...|
+----------+-----------------+-----------------+-------------------+--------------------+--------------------+

In [20]:
# Perform the join operation
dim_payment = payment_df.alias("p").join(
    combined_df.alias("c"),
    (col("p.payment_method_id") == col("c.payment_method_id")) &
    (col("p.payment_status_id") == col("c.payment_status_id")),
    "inner"  # Use "inner" for only matching records
).select(
    col("p.payment_id").alias("s_payment"),  # Select from payment_df
    col("c.method_name").alias("method"),  # Select from combined_df
    col("c.status_name").alias("status")  # Select from combined_df
)

# Show the resulting DataFrame
dim_payment.show(50)

+---------+-----------+---------+
|s_payment|     method|   status|
+---------+-----------+---------+
|        1|  Apple Pay|Completed|
|        2|       Cash|  Pending|
|        3|Credit Card|Completed|
|        4| Debit Card| Refunded|
|        5| Google Pay|   Failed|
|        6|     PayPal| Refunded|
+---------+-----------+---------+

In [21]:
dim_location = location_df.select("location_id", "latitude", "longitude")
dim_location.show()

+-----------+-----------+------------+
|location_id|   latitude|   longitude|
+-----------+-----------+------------+
|     140808|40.74440384|-73.99198151|
|    1099001|40.72247696|-73.98711395|
|     419142|40.75440979|-73.96898651|
|     405519|40.76442337| -73.9709549|
|     428147|40.75773621|-73.96775818|
|     232211|40.74724197|-73.98554993|
|    1435854|40.76414871|-73.96662903|
|    1024948|40.73995972|-73.98249054|
|    1601613|40.75263977|-73.96591949|
|    1100722|40.77864838| -73.9495163|
|     564879|40.64452744|-73.78232574|
|     963528| 40.6946106|-73.95597839|
|     496545|40.77680206|-73.95554352|
|     300123|40.76207352|-73.98092651|
|    1216556|40.75581741|  -73.961586|
|    1120793|40.75146103|-73.98009491|
|     163818|40.75507355|-73.99047852|
|       8554|40.70281219|-74.01144409|
|    1682356|40.77541351|-73.95649719|
|     543786|40.76676178|-73.92095947|
+-----------+-----------+------------+
only showing top 20 rows

In [22]:
request_df.show(5)
trip_df.show(5)

+----------+------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+
|request_id|passenger_id|pickup_location_id|dropoff_location_id|       request_time|        accept_time|    processing_date|record_modified_date|         record_hash|
+----------+------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+
|    447450|      224189|            376530|             338646|2015-01-04 15:28:00|2015-01-04 15:30:00|2024-10-13 19:45:15|2024-10-08 09:47:...|02018d1c2a52d91dd...|
|    433893|      217445|            562731|             567647|2015-01-29 12:34:00|2015-01-29 12:44:00|2024-10-13 19:45:15|2024-10-08 09:47:...|eef0dbb103d3fbc24...|
|    178990|       88035|            544948|             513195|2015-01-30 17:50:00|2015-01-30 17:51:00|2024-10-13 19:45:15|2024-10-08 09:47:...|536eeb49f7dca596d...|
|    379467|      189160|            500234|             377330|2015-01-22 17:42:00|2015-01-22 17:49:00|2024-10-13 19:45:15|2024-10-08 09:47:...|abc91cee122aad675...|
|    542452|      271225|            221413|             555053|2015-01-19 03:17:00|2015-01-19 03:21:00|2024-10-13 19:45:15|2024-10-08 09:47:...|c6913cfeb8c196e6c...|
+----------+------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+
only showing top 5 rows

+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
|trip_id|request_id|driver_id|vehicle_id|payment_id|    trip_start_time|      trip_end_time|trip_distance|base_fare|extra_fare|mta_tax|tip_amount|tolls_amount|improvement_surcharge|    processing_date|record_modified_date|         record_hash|
+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
|  52273|    387479|  1133778|    241226|         6|2015-01-06 08:17:00|2015-01-06 08:21:00|         0.57|      4.5|       0.0|    0.5|      1.35|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|55eac87a0175d172d...|
|  52513|    304466|  1071291|     75238|         4|2015-01-09 12:50:00|2015-01-09 12:54:00|         0.59|      4.5|       0.0|    0.5|      1.12|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|05cbe877f3906106f...|
|  52972|    245931|   852437|     14760|         5|2015-01-05 09:50:00|2015-01-05 10:02:00|         0.93|      9.0|       0.0|    0.5|       1.8|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|62548ea3a4073f729...|
|  53208|     42995|  1011310|    365818|         1|2015-01-01 07:26:00|2015-01-01 07:37:00|          3.0|     11.5|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|8d145f20fdc0b771c...|
|  53282|    413323|  1032813|    114089|         6|2015-01-04 00:17:00|2015-01-04 00:25:00|          1.5|      8.0|       0.5|    0.5|       1.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|78e5c0b3811b92585...|
+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
only showing top 5 rows

In [23]:
# Join the DataFrames
fact_request = request_df.join(trip_df, request_df["request_id"] == trip_df["request_id"], "left") \
    .join(dim_payment, trip_df["payment_id"] == dim_payment["s_payment"], "left") \
    .select(
        trip_df["driver_id"],
        request_df["passenger_id"],
        request_df["pickup_location_id"],
        request_df["dropoff_location_id"],
        date_format(request_df["request_time"], 'yyyyMMdd').alias("request_datekey"),  # Renamed and formatted
        date_format(request_df["accept_time"], 'yyyyMMdd').alias("accept_datekey"),    # Renamed and formatted
        date_format(trip_df["trip_start_time"], 'yyyyMMdd').alias("trip_start_datekey"),   # Renamed
        date_format(trip_df["trip_end_time"], 'yyyyMMdd').alias("trip_end_datekey"),       # Renamed
        dim_payment["s_payment"],
        trip_df["trip_distance"],
        trip_df["base_fare"],
        trip_df["extra_fare"],
        trip_df["mta_tax"],
        trip_df["tip_amount"],
        trip_df["tolls_amount"],
        trip_df["improvement_surcharge"]
    )


# Show the resulting DataFrame
fact_request.show(10)

+---------+------------+------------------+-------------------+---------------+--------------+------------------+----------------+---------+-------------+---------+----------+-------+----------+------------+---------------------+
|driver_id|passenger_id|pickup_location_id|dropoff_location_id|request_datekey|accept_datekey|trip_start_datekey|trip_end_datekey|s_payment|trip_distance|base_fare|extra_fare|mta_tax|tip_amount|tolls_amount|improvement_surcharge|
+---------+------------+------------------+-------------------+---------------+--------------+------------------+----------------+---------+-------------+---------+----------+-------+----------+------------+---------------------+
|   951731|         801|            384446|             313498|       20150102|      20150102|          20150102|        20150102|        6|          0.5|      4.0|       1.0|    0.5|       0.0|         0.0|                  0.0|
|  1006899|       17348|            402794|             289862|       20150118|      20150118|          20150118|        20150118|        3|          0.9|      6.5|       0.0|    0.5|       1.0|         0.0|                  0.3|
|   979236|       31220|            313390|             394421|       20150123|      20150123|          20150123|        20150123|        4|         2.13|      9.0|       0.5|    0.5|       0.0|         0.0|                  0.3|
|   896220|       53148|             13844|             178701|       20150123|      20150123|          20150123|        20150123|        4|         2.82|     14.0|       1.0|    0.5|       2.0|         0.0|                  0.3|
|  1006017|       80654|            437951|             515385|       20150107|      20150107|          20150107|        20150107|        2|          3.3|     16.5|       0.0|    0.5|      3.46|         0.0|                  0.3|
|  1015186|      131856|            400761|             174783|       20150131|      20150131|          20150131|        20150131|        4|         1.44|      9.0|       0.0|    0.5|      1.96|         0.0|                  0.3|
|  1091577|      142440|            466278|             415733|       20150116|      20150116|          20150116|        20150116|        6|          4.9|     18.5|       1.0|    0.5|       2.0|         0.0|                  0.3|
|  1120972|      151808|             96504|             463717|       20150117|      20150117|          20150117|        20150117|        2|          4.5|     23.0|       0.5|    0.5|       3.0|         0.0|                  0.3|
|  1086371|      153650|            154479|             235357|       20150116|      20150116|          20150116|        20150116|        2|          1.6|      8.5|       0.0|    0.5|       1.0|         0.0|                  0.3|
|   889790|      170508|             61371|             111008|       20150121|      20150121|          20150121|        20150121|        6|         2.73|     13.5|       0.0|    0.5|      3.58|         0.0|                  0.3|
+---------+------------+------------------+-------------------+---------------+--------------+------------------+----------------+---------+-------------+---------+----------+-------+----------+------------+---------------------+
only showing top 10 rows

In [46]:
dataframes = [dim_calendar, dim_location, dim_payment, dim_user, fact_request]
# Names of the original DataFrames
dataframe_names = ["dim_calendar", "dim_location", "dim_payment", "dim_user", "fct_request"]

In [47]:
processing_date = date_trunc('second', current_timestamp())

for i, df in enumerate(dataframes):
    # Apply column name conversion
    df = df.withColumn("processing_date", processing_date)

    # Reassign the modified DataFrame back to the original global variable
    globals()[dataframe_names[i]] = df
    
    # Show the first 5 rows of the updated DataFrame
trip_df.show()

+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
|trip_id|request_id|driver_id|vehicle_id|payment_id|    trip_start_time|      trip_end_time|trip_distance|base_fare|extra_fare|mta_tax|tip_amount|tolls_amount|improvement_surcharge|    processing_date|record_modified_date|         record_hash|
+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
|  52273|    387479|  1133778|    241226|         6|2015-01-06 08:17:00|2015-01-06 08:21:00|         0.57|      4.5|       0.0|    0.5|      1.35|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|55eac87a0175d172d...|
|  52513|    304466|  1071291|     75238|         4|2015-01-09 12:50:00|2015-01-09 12:54:00|         0.59|      4.5|       0.0|    0.5|      1.12|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|05cbe877f3906106f...|
|  52972|    245931|   852437|     14760|         5|2015-01-05 09:50:00|2015-01-05 10:02:00|         0.93|      9.0|       0.0|    0.5|       1.8|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|62548ea3a4073f729...|
|  53208|     42995|  1011310|    365818|         1|2015-01-01 07:26:00|2015-01-01 07:37:00|          3.0|     11.5|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|8d145f20fdc0b771c...|
|  53282|    413323|  1032813|    114089|         6|2015-01-04 00:17:00|2015-01-04 00:25:00|          1.5|      8.0|       0.5|    0.5|       1.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|78e5c0b3811b92585...|
|  53495|    161809|   782193|    157183|         2|2015-01-30 13:39:00|2015-01-30 13:54:00|          1.6|     11.0|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|adf38727653d50e8d...|
|  53621|    279415|  1088014|      8655|         5|2015-01-04 01:12:00|2015-01-04 01:29:00|         3.27|     14.0|       0.5|    0.5|       2.9|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|21eb2cbe65b5ed4d3...|
|  53622|    116098|   972558|    187409|         4|2015-01-04 01:12:00|2015-01-04 01:21:00|         1.93|      8.5|       0.5|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|32402830a3d32ecf6...|
|  54210|    459025|  1102298|    165269|         4|2015-01-08 07:55:00|2015-01-08 08:03:00|          1.0|      7.0|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|7868cc939dca082fd...|
|  54285|    114521|  1038363|     71464|         6|2015-01-15 09:04:00|2015-01-15 09:32:00|         4.29|     20.5|       0.0|    0.5|       4.1|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|c62460e4091ed590a...|
|  54539|    352645|  1050452|    204616|         3|2015-01-29 14:01:00|2015-01-29 14:08:00|         0.74|      6.0|       0.0|    0.5|       1.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|802bd6e9e42cd7f53...|
|  54993|      4415|   955995|     38381|         3|2015-01-03 09:19:00|2015-01-03 09:33:00|          2.8|     12.5|       0.0|    0.5|       0.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|cb4fd712fd2fe08bb...|
|  55078|    142419|   840739|    100485|         5|2015-01-05 17:25:00|2015-01-05 17:36:00|         1.41|      9.0|       1.0|    0.5|       1.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|f93bbb9c17a1d196a...|
|  55106|    369660|   934532|    304977|         3|2015-01-04 08:11:00|2015-01-04 08:15:00|          1.3|      6.0|       0.0|    0.5|       0.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|9cc7392e805100299...|
|  55206|    278277|  1093847|    370784|         6|2015-01-04 08:51:00|2015-01-04 08:54:00|          0.6|      4.5|       0.0|    0.5|       0.0|         0.0|                  0.0|2024-10-13 19:45:21|2024-10-08 09:47:...|a91b2c2d640b3c037...|
|  55815|    223062|   984862|    174006|         6|2015-01-10 18:49:00|2015-01-10 19:05:00|         2.17|     12.0|       0.0|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|0d1f163146deb35a8...|
|  55870|    249870|   910307|    121943|         5|2015-01-10 22:14:00|2015-01-10 22:17:00|          0.3|      3.5|       0.5|    0.5|       0.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|dfcd3e1f86d99e6cd...|
|  55896|     17990|   861203|    316846|         5|2015-01-18 12:20:00|2015-01-18 12:36:00|         3.92|     14.5|       0.0|    0.5|       2.0|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|b909eac423130416f...|
|  56020|    106007|   828991|    351557|         1|2015-01-30 14:30:00|2015-01-30 14:38:00|          0.6|      6.5|       0.0|    0.5|      1.45|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|9cc285bbe80d69e2f...|
|  56314|    138783|   837824|    364297|         2|2015-01-16 17:52:00|2015-01-16 17:55:00|         0.42|      4.5|       1.0|    0.5|       0.7|         0.0|                  0.3|2024-10-13 19:45:21|2024-10-08 09:47:...|9a75bba4a6dd73833...|
+-------+----------+---------+----------+----------+-------------------+-------------------+-------------+---------+----------+-------+----------+------------+---------------------+-------------------+--------------------+--------------------+
only showing top 20 rows

In [48]:

# List of DataFrames, locations, and hash columns with an attribute for slowly changing dimension (SCD)
tables_info = [
    {"df": dim_user, "location": f"{gold_location}/DIM_USER", "hash_columns": ["user_id", "full_name"], "is_scd": True},
    {"df": dim_calendar, "location": f"{gold_location}/DIM_CALENDAR", "hash_columns": ["date_key"], "is_scd": False},
    {"df": dim_location, "location": f"{gold_location}/DIM_LOCATION", "hash_columns": ["location_id"], "is_scd": False},
    {"df": dim_payment, "location": f"{gold_location}/DIM_PAYMENT", "hash_columns": ["s_payment"], "is_scd": False},
    {"df": fact_request, "location": f"{gold_location}/FCT_REQUEST", "hash_columns": ["driver_id", "passenger_id", "request_datekey"], "is_scd": False}
]

def deduplicate_source_df(source_df: DataFrame, hash_columns: list) -> DataFrame:
    """
    Deduplicates the source DataFrame based on the hash columns.
    
    Args:
        source_df (DataFrame): The source DataFrame to be deduplicated.
        hash_columns (list): List of columns to be used for deduplication.
        
    Returns:
        DataFrame: The deduplicated DataFrame.
    """
    return source_df.dropDuplicates(hash_columns)

# Function to generate a hash column for specified columns in a DataFrame
def generate_hash_column(df: DataFrame, columns: list, hash_column_name: str = "record_hash") -> DataFrame:
    """
    Generates a hash column for specified columns in the DataFrame using SHA-256.
    """
    return df.withColumn(hash_column_name, sha2(concat_ws("||", *columns), 256))

# Function to build merge condition using hash
def build_merge_condition_with_hash(target_alias: str, source_alias: str, hash_column: str) -> str:
    """
    Builds a merge condition string using the hash column.
    """
    return f"{target_alias}.{hash_column} = {source_alias}.{hash_column}"

# Function to merge Delta tables based on SCD flag
def merge_delta_table(source_df: DataFrame, delta_location: str, hash_columns: list, is_scd: bool):
    """
    Performs merge for slowly changing dimension (SCD) tables. If is_scd is False, data is simply overwritten.
    """
    # Generate hash column for the source DataFrame
    source_df_hashed = generate_hash_column(source_df, hash_columns)
    
    # If the table is an SCD, perform a merge operation
    if is_scd:
        try:
            # Check if the Delta table exists at the specified location
            if DeltaTable.isDeltaTable(spark, delta_location):
                print(f"Delta table found at {delta_location}. Proceeding with merge...")
                delta_table = DeltaTable.forPath(spark, delta_location)
                
                # Alias for target and source
                target_alias = "target"
                source_alias = "src"
                
                # Generate hash column for the target Delta table
                delta_table_df = spark.read.format("delta").load(delta_location)
                delta_table_hashed = generate_hash_column(delta_table_df, hash_columns)
                
                # Build the merge condition using the hash column
                merge_condition = build_merge_condition_with_hash(target_alias, source_alias, "record_hash")
                
                # Perform the merge operation
                delta_table.alias(target_alias).merge(
                    source=source_df_hashed.alias(source_alias),
                    condition=merge_condition
                ).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
                
                print(f"Merge completed for {delta_location}.")
            else:
                # If Delta table doesn't exist, write the DataFrame to that location
                print(f"No Delta table found at {delta_location}. Writing new DataFrame...")
                source_df_hashed.write.mode("overwrite").format("delta").save(delta_location)
                print(f"DataFrame written to {delta_location}.")
        except Exception as e:
            print(f"Error processing table at {delta_location}: {e}")
    else:
        # For non-SCD tables, just overwrite the data
        print(f"{delta_location} is not an SCD table. Overwriting...")
        source_df_hashed.write.mode("overwrite").format("delta").save(delta_location)
        print(f"DataFrame overwritten at {delta_location}.")

In [49]:
# Loop through each table and perform the operations
for table_info in tables_info:
    # Print the schema of the source DataFrame
    print("Schema of source DataFrame:")
    table_info["df"].printSchema()  # Ensure we are printing the schema of the specific DataFrame

    # Deduplicate the source DataFrame based on hash columns
    df = deduplicate_source_df(table_info["df"], table_info["hash_columns"])
    
    # Prepare the Delta table location and SCD flag
    delta_location = table_info["location"]
    hash_columns = table_info["hash_columns"]
    is_scd = table_info["is_scd"]  # Check if it's a slowly changing dimension

    # Perform merge or overwrite based on is_scd flag
    merge_delta_table(df, delta_location, hash_columns, is_scd)

Schema of source DataFrame:
root
 |-- user_id: integer (nullable = true)
 |-- full_name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- phone_number: string (nullable = true)
 |-- vehicle_id: string (nullable = false)
 |-- vehicle_make: string (nullable = false)
 |-- vehicle_model: string (nullable = false)
 |-- vehicle_year: string (nullable = false)
 |-- vehicle_color: string (nullable = false)
 |-- vehicle_license_plate: string (nullable = false)
 |-- processing_date: timestamp (nullable = true)

Delta table found at e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_USER. Proceeding with merge...
Merge completed for e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_USER.
Schema of source DataFrame:
root
 |-- date_key: string (nullable = false)
 |-- full_date: date (nullable = false)
 |-- day: integer (nullable = false)
 |-- day_name: string (nullable = false)
 |-- day_of_week: integer (nullable = false)
 |-- week_of_year: integer (nullable = false)
 |-- month: integer (nullable = false)
 |-- month_name: string (nullable = false)
 |-- quarter: integer (nullable = false)
 |-- year: integer (nullable = false)
 |-- is_weekend: integer (nullable = false)
 |-- is_holiday: integer (nullable = false)
 |-- fiscal_month: integer (nullable = false)
 |-- fiscal_quarter: integer (nullable = false)
 |-- fiscal_year: integer (nullable = false)
 |-- processing_date: timestamp (nullable = true)

e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_CALENDAR is not an SCD table. Overwriting...
DataFrame overwritten at e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_CALENDAR.
Schema of source DataFrame:
root
 |-- location_id: integer (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- processing_date: timestamp (nullable = true)

e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_LOCATION is not an SCD table. Overwriting...
DataFrame overwritten at e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_LOCATION.
Schema of source DataFrame:
root
 |-- s_payment: integer (nullable = true)
 |-- method: string (nullable = true)
 |-- status: string (nullable = true)
 |-- processing_date: timestamp (nullable = true)

e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_PAYMENT is not an SCD table. Overwriting...
DataFrame overwritten at e:\DEPIfINALpROJECT\DATABASEcSV/gold/DIM_PAYMENT.
Schema of source DataFrame:
root
 |-- driver_id: integer (nullable = true)
 |-- passenger_id: integer (nullable = true)
 |-- pickup_location_id: integer (nullable = true)
 |-- dropoff_location_id: integer (nullable = true)
 |-- request_datekey: string (nullable = true)
 |-- accept_datekey: string (nullable = true)
 |-- trip_start_datekey: string (nullable = true)
 |-- trip_end_datekey: string (nullable = true)
 |-- s_payment: integer (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- base_fare: double (nullable = true)
 |-- extra_fare: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- processing_date: timestamp (nullable = true)

e:\DEPIfINALpROJECT\DATABASEcSV/gold/FCT_REQUEST is not an SCD table. Overwriting...
DataFrame overwritten at e:\DEPIfINALpROJECT\DATABASEcSV/gold/FCT_REQUEST.

In [50]:
spark.read.format("delta").load(f"{gold_location}/DIM_USER").orderBy("full_name").show()

+-------+------------+--------------------+--------------+----------+------------+-------------+------------+-------------+---------------------+-------------------+--------------------+
|user_id|   full_name|               email|  phone_number|vehicle_id|vehicle_make|vehicle_model|vehicle_year|vehicle_color|vehicle_license_plate|    processing_date|         record_hash|
+-------+------------+--------------------+--------------+----------+------------+-------------+------------+-------------+---------------------+-------------------+--------------------+
|   NULL|    --------|               -----|   -----------| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|2024-10-13 20:06:57|370d9b71060be968d...|
| 768128|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|2024-10-13 20:06:57|1ec48e73a3376b697...|
| 762535|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|2024-10-13 20:06:57|7c4dfcfb597e8c6e2...|
| 767104|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|2024-10-13 20:06:57|24d00ea8fc1be35ea...|
| 776168|Aaron Abbott|angela67@example.com|(453) 832-3608|    168434|     Hyundai|     Santa Fe|        2006|       Silver|              3BW 116|2024-10-13 20:06:57|408174e83dc4afa4d...|
|      1|Aaron Acosta| account@example.net|(677) 367-9557| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|2024-10-13 20:06:57|21d31195f82942e05...|
| 967068|Aaron Acosta|vanessa20@example...|(953) 599-6007|     11618|         BMW|     5 Series|        2017|       Orange|                 389J|2024-10-13 20:06:57|c4f5b7dba1250f9c8...|
| 850461|Aaron Acosta|vanessa20@example...|(953) 599-6007|     11618|         BMW|     5 Series|        2017|       Orange|                 389J|2024-10-13 20:06:57|9ffbb377c4a47210a...|
| 758776| Aaron Adams|  dbowen@example.net|(672) 995-6696|     75956|        Ford|       Escape|        1996|        Brown|                3G783|2024-10-13 20:06:57|19adffa1d192cbeb1...|
| 933047| Aaron Adams|angela64@example.com|(619) 154-2732|     40923|   Chevrolet|       Camaro|        1997|       Orange|              YNU1270|2024-10-13 20:06:57|de340bcd20afb16a3...|
|      4| Aaron Adams|zjohnson@example.com|(324) 384-5822| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|2024-10-13 20:06:57|60f62b9afaac9bbb8...|
| 755043| Aaron Adams|beckdaniel@exampl...|(987) 878-1073|     52562|   Chevrolet|       Malibu|        2022|        Black|              324 JEN|2024-10-13 20:06:57|f37af311dc85681be...|
|      2| Aaron Adams| james82@example.com|(332) 224-7965| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|2024-10-13 20:06:57|683e6c22fa1e45bef...|
| 869145| Aaron Adams|jesseschwartz@exa...|(250) 242-4652|    172968|     Hyundai|       Sonata|        2006|         Gray|              CQI-168|2024-10-13 20:06:57|092f7cfb9a2639ccc...|
| 757174| Aaron Adams|  dbowen@example.net|(672) 995-6696|     23039|         BMW|           X5|        1996|         Blue|              IIV-491|2024-10-13 20:06:57|d0f0642915afc8d9d...|
| 916376| Aaron Adams|  jill51@example.org|(120) 200-5627|    138962|       Honda|          Fit|        2006|       Silver|              65M 278|2024-10-13 20:06:57|b8b13cd2f9d2014f2...|
|      3| Aaron Adams|monopoly@example.net|(351) 943-8670| Passenger|   Passenger|    Passenger|   Passenger|    Passenger|            Passenger|2024-10-13 20:06:57|500bf842d2becc183...|
| 958105| Aaron Adams|angela64@example.com|(619) 154-2732|     27003|         BMW|           X5|        2006|          Red|              NFD-596|2024-10-13 20:06:57|83ff9b2d18d1e9ad9...|
| 795166| Aaron Adams|  dbowen@example.net|(672) 995-6696|     74881|        Ford|       Escape|        2017|        Black|              0BUG 39|2024-10-13 20:06:57|f6a334f710dd054e2...|
| 934434| Aaron Adams| emily69@example.net|(217) 156-8782|     67661|   Chevrolet|        Tahoe|        1994|         Blue|              YCF 385|2024-10-13 20:06:57|eb653d2a538d2ece4...|
+-------+------------+--------------------+--------------+----------+------------+-------------+------------+-------------+---------------------+-------------------+--------------------+
only showing top 20 rows

In [51]:
# After your write_to_delta function
for table in dataframe_names:
    
    print(f"Creating external table: {table}")
    # Creating schema and external table in Spark SQL
    spark.sql("CREATE SCHEMA IF NOT EXISTS gold")
    # Set the current database to 'gold'
    spark.sql("USE gold")
    delta_table_path = f"{gold_location}\\{table}"
    spark.sql(f"CREATE EXTERNAL TABLE IF NOT EXISTS {table} USING DELTA LOCATION r'{table}'")
    #spark.sql(f"SELECT * FROM {table_name}").show()

Creating external table: dim_calendar
Creating external table: dim_location
Creating external table: dim_payment
Creating external table: dim_user
Creating external table: fct_request

In [52]:
from delta.tables import DeltaTable

# Dictionary to store the DeltaTable objects
delta_tables = {}

for table in dataframe_names:
    # Define the table location
    table_location = f"{gold_location}/{table}"
    print(table_location)
    # Store the DeltaTable object in the dictionary using the file name as the key
    delta_tables[table] = DeltaTable.forPath(spark, table_location)  # Load table from path

    # Check if the table has been vacuumed in the last 30 days
    if delta_tables[table].history(30).filter("operation = 'VACUUM START'").count() == 0:
        # Optimize the table for better query performance
        delta_tables[table].optimize()
        # Perform vacuum operation (default is to keep data for 7 days)
        delta_tables[table].vacuum()

e:\DEPIfINALpROJECT\DATABASEcSV/gold/dim_calendar
e:\DEPIfINALpROJECT\DATABASEcSV/gold/dim_location
e:\DEPIfINALpROJECT\DATABASEcSV/gold/dim_payment
e:\DEPIfINALpROJECT\DATABASEcSV/gold/dim_user
e:\DEPIfINALpROJECT\DATABASEcSV/gold/fct_request

In [73]:
spark.read.format("delta").load(f"{gold_location}/FCT_REQUEST").count()

584871

In [68]:
from delta.tables import *

deltaTable = DeltaTable.forPath(spark, "gold\\FCT_REQUEST")
fullHistoryDF = deltaTable.history()
fullHistoryDF.show(truncate=False)

+-------+-----------------------+------+--------+------------+--------------------------------------------------------------------+----+--------+---------+-----------+-----------------+-------------+---------------------------------------------------------------------+------------+-----------------------------------+
|version|timestamp              |userId|userName|operation   |operationParameters                                                 |job |notebook|clusterId|readVersion|isolationLevel   |isBlindAppend|operationMetrics                                                     |userMetadata|engineInfo                         |
+-------+-----------------------+------+--------+------------+--------------------------------------------------------------------+----+--------+---------+-----------+-----------------+-------------+---------------------------------------------------------------------+------------+-----------------------------------+
|4      |2024-10-13 20:07:59.897|NULL  |NULL    |VACUUM END  |{status -> COMPLETED}                                               |NULL|NULL    |NULL     |3          |SnapshotIsolation|true         |{numDeletedFiles -> 0, numVacuumedDirectories -> 1}                  |NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|3      |2024-10-13 20:07:58.711|NULL  |NULL    |VACUUM START|{retentionCheckEnabled -> true, defaultRetentionMillis -> 604800000}|NULL|NULL    |NULL     |2          |SnapshotIsolation|true         |{numFilesToDelete -> 0, sizeOfDataToDelete -> 0}                     |NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|2      |2024-10-13 20:07:35.508|NULL  |NULL    |WRITE       |{mode -> Overwrite, partitionBy -> []}                              |NULL|NULL    |NULL     |1          |Serializable     |false        |{numFiles -> 13, numOutputRows -> 584871, numOutputBytes -> 52346654}|NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|1      |2024-10-13 19:59:56.507|NULL  |NULL    |WRITE       |{mode -> Overwrite, partitionBy -> []}                              |NULL|NULL    |NULL     |0          |Serializable     |false        |{numFiles -> 13, numOutputRows -> 584871, numOutputBytes -> 52346654}|NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
|0      |2024-10-13 19:50:44.739|NULL  |NULL    |WRITE       |{mode -> Overwrite, partitionBy -> []}                              |NULL|NULL    |NULL     |NULL       |Serializable     |false        |{numFiles -> 13, numOutputRows -> 584871, numOutputBytes -> 52346641}|NULL        |Apache-Spark/3.5.3 Delta-Lake/3.2.0|
+-------+-----------------------+------+--------+------------+--------------------------------------------------------------------+----+--------+---------+-----------+-----------------+-------------+---------------------------------------------------------------------+------------+-----------------------------------+

In [53]:
# Join the DataFrames with aliases for clarity
"""
fact_request_with_user_payment = fact_request.alias("fr") \
    .join(dim_user.alias("du"), col("fr.driver_id") == col("du.user_id"), "left") \
    .join(dim_user.alias("pu"), col("fr.passenger_id") == col("pu.user_id"), "left") \
    .join(dim_payment.alias("dp"), col("fr.s_payment") == col("dp.s_payment"), "left") \
    .select(
        col("fr.driver_id"),
        col("fr.passenger_id"),
        col("fr.pickup_location_id"),
        col("fr.dropoff_location_id"),
        col("fr.request_datekey"),
        col("fr.accept_datekey"),
        col("fr.trip_start_datekey"),
        col("fr.trip_end_datekey"),
        col("fr.s_payment"),
        col("fr.trip_distance"),
        col("fr.base_fare"),
        col("fr.extra_fare"),
        col("fr.mta_tax"),
        col("fr.tip_amount"),
        col("fr.tolls_amount"),
        col("fr.improvement_surcharge"),
        col("du.full_name").alias("driver_name"),
        col("du.email").alias("driver_email"),
        col("du.phone_number").alias("driver_phone"),
        col("du.vehicle_id").alias("driver_vehicle_id"),
        col("du.vehicle_make").alias("driver_vehicle_make"),
        col("du.vehicle_model").alias("driver_vehicle_model"),
        col("du.vehicle_year").alias("driver_vehicle_year"),
        col("du.vehicle_color").alias("driver_vehicle_color"),
        col("du.vehicle_license_plate").alias("driver_vehicle_license_plate"),
        col("pu.full_name").alias("passenger_name"),
        col("pu.email").alias("passenger_email"),
        col("pu.phone_number").alias("passenger_phone"),
        col("dp.method").alias("payment_method"),
        col("dp.status").alias("payment_status")
    )

# Show the resulting DataFrame
fact_request_with_user_payment.orderBy("driver_name").show(10)
"""

'\nfact_request_with_user_payment = fact_request.alias("fr")     .join(dim_user.alias("du"), col("fr.driver_id") == col("du.user_id"), "left")     .join(dim_user.alias("pu"), col("fr.passenger_id") == col("pu.user_id"), "left")     .join(dim_payment.alias("dp"), col("fr.s_payment") == col("dp.s_payment"), "left")     .select(\n        col("fr.driver_id"),\n        col("fr.passenger_id"),\n        col("fr.pickup_location_id"),\n        col("fr.dropoff_location_id"),\n        col("fr.request_datekey"),\n        col("fr.accept_datekey"),\n        col("fr.trip_start_datekey"),\n        col("fr.trip_end_datekey"),\n        col("fr.s_payment"),\n        col("fr.trip_distance"),\n        col("fr.base_fare"),\n        col("fr.extra_fare"),\n        col("fr.mta_tax"),\n        col("fr.tip_amount"),\n        col("fr.tolls_amount"),\n        col("fr.improvement_surcharge"),\n        col("du.full_name").alias("driver_name"),\n        col("du.email").alias("driver_email"),\n        col("du.phone_number").alias("driver_phone"),\n        col("du.vehicle_id").alias("driver_vehicle_id"),\n        col("du.vehicle_make").alias("driver_vehicle_make"),\n        col("du.vehicle_model").alias("driver_vehicle_model"),\n        col("du.vehicle_year").alias("driver_vehicle_year"),\n        col("du.vehicle_color").alias("driver_vehicle_color"),\n        col("du.vehicle_license_plate").alias("driver_vehicle_license_plate"),\n        col("pu.full_name").alias("passenger_name"),\n        col("pu.email").alias("passenger_email"),\n        col("pu.phone_number").alias("passenger_phone"),\n        col("dp.method").alias("payment_method"),\n        col("dp.status").alias("payment_status")\n    )\n\n# Show the resulting DataFrame\nfact_request_with_user_payment.orderBy("driver_name").show(10)\n'